apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homework-app.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "homework-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
