{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homework-app.fullname" . }}-pvc
  labels:
    app.kubernetes.io/name: {{ include "homework-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes: 
{{ toYaml .Values.persistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
