{{- if .Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name | default "default-storage-class" }}
provisioner: {{ .Values.storageClass.provisioner | default "k8s.io/minikube-hostpath" }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy | default "Retain" }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode | default "Immediate" }}
{{- end }}

