apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;

            location / {
                root /usr/share/nginx/html;  # Путь к директории, откуда NGINX будет обслуживать файлы
                index index.html;            # Главная страница, которую NGINX будет отображать по запросу "/"
                try_files $uri $uri/ =404;   # Если файл не найден, вернется ошибка 404
            }

            # Endpoint для метрик
            location /stub_status {
                stub_status;
                allow all;  # Рекомендуется ограничить доступ по IP в продакшене
            }
        }
    }
