apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  #namespace: homework
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http 
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113
  type: LoadBalancer
  #type: ClusterIP