---
repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: promatil
  namespace: monitoring
  chart: grafana/promtail
  version: 6.15.5
  values: 
  - values.yaml