apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-role-binding
subjects:
  - kind: ServiceAccount
    name: mysql-operator-controller-manager
    namespace: mysql-operator-system
roleRef:
  kind: ClusterRole
  name: manager-role
  apiGroup: rbac.authorization.k8s.io
